import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/components/layout/AuthProvider";
import { ErrorBoundary } from "@/components/layout/ErrorBoundary";
import { InstallPrompt } from "@/components/layout/InstallPrompt";
import { NavigationWrapper } from "@/components/layout/NavigationWrapper";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`dark h-full ${inter.variable} antialiased`}>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#0a0a0a" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta name="apple-mobile-web-app-title" content="AetherOS" />
        <link rel="apple-touch-icon" href="/icon-192.png" />
        <meta name="mobile-web-app-capable" content="yes" />
      </head>
      <body className="flex min-h-full flex-col bg-[#0a0a0a] text-foreground">
        <AuthProvider>
          <NavigationWrapper>
            <ErrorBoundary>{children}</ErrorBoundary>
          </NavigationWrapper>
          <InstallPrompt />
        </AuthProvider>
      </body>
    </html>
  );
}
